### PR TITLE
Fix 'rename' prompt with prepopulated value

### PR DESCRIPTION
**Pull request by cody-vibe**
Hello, had a day off today so I thought I'd tackle something that has been annoying me for a while now.

The second argument for `read-string` is `INITIAL-INPUT` which is used
to pre-populate the minibuffer, the fourth `DEFAULT-VALUE` is what it
returns in case the prompt has an empty string.

While the docs for `read-string` say `INITIAL-INPUT` has been superseded
by `DEFAULT-VALUE`, this is misleading as `DEFAULT-VALUE` by itself does
not pre-populate the minibuffer.

Example code:

```elisp
;; No pre-completed value, returns "" when empty.
(read-string "PROMPT ")

;; Pre-completed with "A", returns "" when empty.
(read-string "PROMPT " "A")

;; Pre-completed with "A", returns "B" when empty.
(read-string "PROMPT " "A" nil "B")

;; No pre-completed value, returns "B" when empty.
(read-string "PROMPT " nil nil "B")
```

Similar changes need to be done in treemacs (and all packages that use `read-string` (I can do that if this PR is accepted). I'll also write in he emacs mailing list about the weird `read-string` docs:

https://debbugs.gnu.org/cgi/bugreport.cgi?bug=50811

### CODE REVIEW

**Comment by Alexander-Miller** [comment]
Given the cfrs api shouldn't the `default-value` argument be nil? For now cfrs only supports an initial input, but not history switching, nor a default value. If you confirm with an empty input cfrs will return an empty string.

**Comment by sdwolfz** [comment]
@Alexander-Miller you can't really have a file name that's blank, so "do nothing" when it's empty is a good approach. I can remove the default value if this error case is handled somewhere else.

**Comment by Alexander-Miller** [comment]
> you can't really have a file name that's blank, so "do nothing" when it's empty is a good approach

That's true for files, but cfrs is meant as a general `read-string` enhancement. So it should be able to deal with situations where returning nothing is a valid approach. 

Having thought it over a bit more here's my plan: for now let's just change the call to `(read-string prompt initial-input)`. That way the fallback will not behave differently from the child-frame input, since the latter uses the initial input without history.

As a next step I will extend cfrs to support using mini-buffer history and the `history` argument, properly aligning cfrs' api to that of read-string. That will be a non-trivial undertaking, so this PR will serve as a useful stopgap measure.

WDYT?

**Comment by Alexander-Miller** [comment]
:+1:

**Comment by Alexander-Miller** [comment]
I've opened a reminder for history support here: https://github.com/Alexander-Miller/cfrs/issues/7

**Pull request merged**
